wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/aircraft carrier.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/airplane.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/alarm clock.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/ambulance.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/angel.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/animal migration.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/ant.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/anvil.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/apple.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/arm.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/asparagus.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/axe.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/backpack.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/banana.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bandage.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/barn.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/baseball.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/baseball bat.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/basket.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/basketball.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bat.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bathtub.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/beach.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bear.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/beard.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bed.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bee.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/belt.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bench.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bicycle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/binoculars.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bird.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/birthday cake.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/blackberry.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/blueberry.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/book.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/boomerang.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bottlecap.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bowtie.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bracelet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/brain.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bread.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bridge.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/broccoli.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/broom.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bucket.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bulldozer.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bus.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/bush.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/butterfly.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cactus.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cake.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/calculator.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/calendar.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/camel.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/camera.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/camouflage.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/campfire.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/candle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cannon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/canoe.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/car.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/carrot.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/castle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cat.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/ceiling fan.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cello.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cell phone.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/chair.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/chandelier.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/church.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/circle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/clarinet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/clock.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cloud.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/coffee cup.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/compass.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/computer.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cookie.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cooler.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/couch.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cow.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/crab.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/crayon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/crocodile.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/crown.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cruise ship.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/cup.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/diamond.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/dishwasher.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/diving board.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/dog.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/dolphin.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/donut.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/door.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/dragon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/dresser.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/drill.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/drums.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/duck.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/dumbbell.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/ear.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/elbow.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/elephant.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/envelope.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/eraser.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/eye.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/eyeglasses.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/face.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/fan.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/feather.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/fence.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/finger.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/fire hydrant.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/fireplace.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/firetruck.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/fish.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/flamingo.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/flashlight.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/flip flops.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/floor lamp.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/flower.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/flying saucer.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/foot.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/fork.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/frog.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/frying pan.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/garden.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/garden hose.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/giraffe.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/goatee.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/golf club.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/grapes.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/grass.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/guitar.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hamburger.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hammer.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hand.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/harp.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hat.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/headphones.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hedgehog.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/helicopter.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/helmet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hexagon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hockey puck.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hockey stick.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/horse.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hospital.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hot air balloon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hot dog.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hot tub.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hourglass.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/house.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/house plant.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/hurricane.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/ice cream.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/jacket.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/jail.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/kangaroo.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/key.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/keyboard.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/knee.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/knife.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/ladder.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lantern.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/laptop.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/leaf.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/leg.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/light bulb.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lighter.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lighthouse.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lightning.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/line.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lion.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lipstick.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lobster.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/lollipop.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mailbox.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/map.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/marker.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/matches.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/megaphone.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mermaid.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/microphone.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/microwave.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/monkey.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/moon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mosquito.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/motorbike.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mountain.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mouse.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/moustache.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mouth.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mug.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/mushroom.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/nail.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/necklace.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/nose.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/ocean.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/octagon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/octopus.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/onion.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/oven.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/owl.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/paintbrush.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/paint can.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/palm tree.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/panda.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pants.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/paper clip.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/parachute.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/parrot.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/passport.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/peanut.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pear.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/peas.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pencil.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/penguin.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/piano.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pickup truck.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/picture frame.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pig.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pillow.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pineapple.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pizza.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pliers.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/police car.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pond.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pool.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/popsicle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/postcard.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/potato.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/power outlet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/purse.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/rabbit.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/raccoon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/radio.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/rain.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/rainbow.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/rake.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/remote control.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/rhinoceros.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/rifle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/river.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/roller coaster.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/rollerskates.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sailboat.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sandwich.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/saw.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/saxophone.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/school bus.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/scissors.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/scorpion.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/screwdriver.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sea turtle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/see saw.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/shark.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sheep.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/shoe.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/shorts.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/shovel.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sink.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/skateboard.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/skull.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/skyscraper.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sleeping bag.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/smiley face.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/snail.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/snake.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/snorkel.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/snowflake.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/snowman.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/soccer ball.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sock.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/speedboat.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/spider.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/spoon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/spreadsheet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/square.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/squiggle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/squirrel.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/stairs.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/star.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/steak.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/stereo.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/stethoscope.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/stitches.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/stop sign.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/stove.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/strawberry.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/streetlight.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/string bean.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/submarine.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/suitcase.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sun.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/swan.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sweater.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/swing set.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/sword.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/syringe.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/table.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/teapot.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/teddy-bear.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/telephone.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/television.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/tennis racquet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/tent.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/The Eiffel Tower.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/The Great Wall of China.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/The Mona Lisa.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/tiger.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/toaster.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/toe.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/toilet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/tooth.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/toothbrush.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/toothpaste.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/tornado.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/tractor.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/traffic light.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/train.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/tree.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/triangle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/trombone.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/truck.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/trumpet.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/t-shirt.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/umbrella.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/underwear.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/van.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/vase.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/violin.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/washing machine.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/watermelon.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/waterslide.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/whale.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/wheel.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/windmill.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/wine bottle.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/wine glass.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/wristwatch.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/yoga.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/zebra.npy"
wget "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/zigzag.npy"
